version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: shrsyc/dd_mean_backend
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db

  frontend:
    image: shrsyc/dd_mean_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
